### ISSUE TITLE
与MythicDungeons的冲突

### ISSUE THREAD

**Issue by ghost** [MkbaKa/ExecutableBlock#2]
版本：purpur-1.19.4-1985（v1_19_R3）
MythicDungeons版本1.2.2
EB版本1.0.7

[22:32:26 ERROR]: Error occurred while enabling ExecutableBlock v1.0.7 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: loader 'ExecutableBlock-1.0.7.jar' @b3dc91c wants to load class javassist.bytecode.AttributeInfo. A different class with the same name was previously loaded by 'MythicDungeons-1.2.2-SNAPSHOT.jar' @64cf3901. (javassist.bytecode.AttributeInfo is in unnamed module of loader 'MythicDungeons-1.2.2-SNAPSHOT.jar' @64cf3901, parent loader java.net.URLClassLoader @7fbe847c)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:236) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at org.reflections.scanners.Scanners$2.scan(Scanners.java:68) ~[ExecutableBlock-1.0.7.jar:?]
        at org.reflections.scanners.Scanners.scan(Scanners.java:200) ~[ExecutableBlock-1.0.7.jar:?]
        at me.mkbaka.executableblock.org.reflections.Reflections.lambda$scan$2(Reflections.java:186) ~[ExecutableBlock-1.0.7.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223) ~[?:?]
        at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915) ~[?:?]
        at java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
        at me.mkbaka.executableblock.org.reflections.Reflections.scan(Reflections.java:173) ~[ExecutableBlock-1.0.7.jar:?]
        at me.mkbaka.executableblock.org.reflections.Reflections.<init>(Reflections.java:126) ~[ExecutableBlock-1.0.7.jar:?]
        at me.mkbaka.executableblock.internal.autoregister.AutoRegisterScanner.scanClasses(AutoRegisterScanner.kt:23) ~[ExecutableBlock-1.0.7.jar:?]
        at me.mkbaka.executableblock.internal.autoregister.AutoRegisterFrame.<init>(AutoRegisterFrame.kt:26) ~[ExecutableBlock-1.0.7.jar:?]
        at me.mkbaka.executableblock.ExecutableBlock.onEnable(ExecutableBlock.kt:24) ~[ExecutableBlock-1.0.7.jar:?]
        at me.mkbaka.executableblock.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:120) ~[ExecutableBlock-1.0.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1985]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ghost** [comment]
补充: 插件最开始正常加载，没有问题，但在之后注册了一个全局监听器以后服务端崩溃，再次重启后出现次错误，插件无法加载
